/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportmanagement;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Maxwell
 */
public class Booking extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private String gender;
    
    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        conn = dbConnect.cone();
        update_table();
        update_tableBook();
        Fillcombo();
        jComboBoxVid.setSelectedItem(null);
        jComboBoxVID.setSelectedItem(null);
        
    }
    
     private void update_table()
    {
        try{
        String sql = "select * from daily";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jTableDaily.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }
     
      private void update_tableBook()
    {
        try{
        String sql = "select * from booking";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jTablebooking.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }
     
     
     private void Fillcombo()
    {
        try
        {
           String sql = "select * from vehicleDetails"; 
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
    
           while(rs.next())
           {
               int name = rs.getInt("vId");
               jComboBoxVid.addItem(name);
               jComboBoxVID.addItem(name);
                
            }
          

        }
        catch(Exception e)
                {
                   JOptionPane.showMessageDialog(null, e); 
                }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jDateChooserDaily = new com.toedter.calendar.JDateChooser();
        jTextFieldFuelLitre = new javax.swing.JTextField();
        jTextFieldOilLitre = new javax.swing.JTextField();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jTextFieldDId = new javax.swing.JTextField();
        jTextFieldClean = new javax.swing.JTextField();
        jTextFieldfuelCost = new javax.swing.JTextField();
        jTextFieldOilCost = new javax.swing.JTextField();
        jTextFielddriveCost = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextFieldtotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        update_txt = new javax.swing.JButton();
        clear_txt = new javax.swing.JButton();
        save = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDaily = new javax.swing.JTable();
        jTextField32 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jComboBoxVid = new javax.swing.JComboBox();
        jLabel44 = new javax.swing.JLabel();
        jTextFielddaily = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextFieldTrip = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldcusName = new javax.swing.JTextField();
        jTextFieldpNumber = new javax.swing.JTextField();
        jTextFieldkin = new javax.swing.JTextField();
        jComboBoxadult = new javax.swing.JComboBox();
        jComboBoxchild = new javax.swing.JComboBox();
        jComboBoxinfant = new javax.swing.JComboBox();
        jLabel45 = new javax.swing.JLabel();
        jTextFieldkinPhone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldbookRef = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDateChooserdepartD = new com.toedter.calendar.JDateChooser();
        jDateChooserreturn = new com.toedter.calendar.JDateChooser();
        jComboBoxdepartT = new javax.swing.JComboBox();
        jTextFieldDstation = new javax.swing.JTextField();
        jTextFielddestin = new javax.swing.JTextField();
        jTextFieldfareP = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextFieldtripId = new javax.swing.JTextField();
        jTextFieldseatNo = new javax.swing.JTextField();
        jComboBoxVID = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablebooking = new javax.swing.JTable();
        jButtonupD = new javax.swing.JButton();
        jButtondele = new javax.swing.JButton();
        jButtonCleart = new javax.swing.JButton();
        jTextField23 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonHome.setText("Home Page");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText(" Booking & Reservation / Daily Task");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N

        jLabel30.setText("Vehicle ID:");

        jLabel31.setText("Driver's Id:");

        jLabel32.setText("Date:");

        jLabel33.setText("Diesel/Fuel Litre:");

        jLabel34.setText("Oil Litre:");

        jLabel35.setText("Diesel/Fuel expense:");

        jLabel37.setText("Oil expense:");

        jLabel38.setText("Cleaning expense:");

        jLabel39.setText("Vehicle Checkup:");

        jLabel40.setText("Driver's earnings:");

        buttonGroup1.add(jRadioButtonYes);
        jRadioButtonYes.setText("Yes");
        jRadioButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonYesActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonNo);
        jRadioButtonNo.setText("No");
        jRadioButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoActionPerformed(evt);
            }
        });

        jTextFieldDId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDIdActionPerformed(evt);
            }
        });

        jLabel41.setText("Total Expense:");

        jTextFieldtotal.setEditable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controls", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 0, 204))); // NOI18N

        update_txt.setText("Update");
        update_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_txtActionPerformed(evt);
            }
        });

        clear_txt.setText("Clear");
        clear_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_txtActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(255, 0, 153));
        save.setForeground(new java.awt.Color(0, 51, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(update_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(update_txt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(save)
                        .addGap(18, 18, 18)
                        .addComponent(del)))
                .addGap(18, 18, 18)
                .addComponent(clear_txt)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTableDaily.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDaily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDailyMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDaily);

        jTextField32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField32KeyReleased(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 204));
        jLabel42.setText("Search:");

        jComboBoxVid.setEditable(true);
        jComboBoxVid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxVidFocusGained(evt);
            }
        });
        jComboBoxVid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVidActionPerformed(evt);
            }
        });
        jComboBoxVid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxVidKeyPressed(evt);
            }
        });

        jLabel44.setText("Daily task Reference:");

        jLabel46.setText("Trip Id:");

        jButton1.setText("c");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("c");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldOilLitre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel39))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonYes)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooserDaily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxVid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldFuelLitre, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTrip)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldOilCost, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel40)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFielddriveCost, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel38)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldClean, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(25, 25, 25)
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldDId, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel35)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldfuelCost, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)))
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFielddaily, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jTextFieldDId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxVid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(jTextFielddaily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel32)
                                .addComponent(jLabel38)
                                .addComponent(jTextFieldClean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooserDaily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel35)
                            .addComponent(jTextFieldFuelLitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldfuelCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jLabel37)
                            .addComponent(jTextFieldOilLitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOilCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel40)
                                    .addComponent(jTextFielddriveCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel39)
                                    .addComponent(jRadioButtonYes)
                                    .addComponent(jRadioButtonNo))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46)
                            .addComponent(jLabel41)
                            .addComponent(jTextFieldtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Daily Task", jPanel2);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel3.setText("Customer Name:");

        jLabel4.setText("Phone Number:");

        jLabel5.setText("Next of kin:");

        jLabel6.setText("Adults:");

        jLabel7.setText("Children:");

        jLabel8.setText("Infants:");

        jComboBoxadult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jComboBoxadult.setSelectedIndex(-1);

        jComboBoxchild.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jComboBoxchild.setSelectedIndex(-1);

        jComboBoxinfant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jComboBoxinfant.setSelectedIndex(-1);

        jLabel45.setText("Next of kin Phone Number:");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxadult, 0, 57, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxchild, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxinfant, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldpNumber)
                                    .addComponent(jTextFieldcusName)
                                    .addComponent(jTextFieldkin, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldkinPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldcusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldpNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jTextFieldkinPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxadult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxchild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxinfant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextFieldcusName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextFieldpNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextFieldkin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboBoxadult, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboBoxchild, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboBoxinfant, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel45, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextFieldkinPhone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Receipt Refrence ID:");

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservation Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel9.setText("Departure Date:");

        jLabel10.setText("Departure Time:");

        jLabel11.setText("Departure Station:");

        jLabel12.setText("Destination:");

        jLabel13.setText("Return Date:");

        jLabel14.setText("Seat No:");

        jLabel16.setText("Fare Paid:");

        jComboBoxdepartT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "06:00AM", "07:00AM", "08:00AM", "09:00AM", "10:00AM" }));
        jComboBoxdepartT.setSelectedIndex(-1);

        jLabel15.setText("Vehicle ID:");

        jLabel43.setText("Trip ID:");

        jComboBoxVID.setEditable(true);

        jButton3.setText("c");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDstation, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldtripId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFielddestin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldfareP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(jComboBoxVID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)))))
                        .addGap(118, 118, 118))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxdepartT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooserdepartD, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooserreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldseatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(jDateChooserdepartD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserreturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxdepartT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(jTextFieldtripId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldDstation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddestin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldseatNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxVID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldfareP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jDateChooserdepartD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jDateChooserreturn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jComboBoxdepartT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldDstation, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFielddestin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldfareP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel43, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldtripId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextFieldseatNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jComboBoxVID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonSave.setText("Save & Print Ticket");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jTablebooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablebooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablebookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablebooking);

        jButtonupD.setText("Update");
        jButtonupD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupDActionPerformed(evt);
            }
        });

        jButtondele.setText("Delete");
        jButtondele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleActionPerformed(evt);
            }
        });

        jButtonCleart.setText("Clear Fields");
        jButtonCleart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleartActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 204));
        jLabel36.setText("Search:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonupD)
                .addGap(18, 18, 18)
                .addComponent(jButtondele)
                .addGap(18, 18, 18)
                .addComponent(jButtonCleart)
                .addGap(62, 62, 62))
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldbookRef, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(32, 32, 32)
                                .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldbookRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonupD)
                        .addComponent(jButtondele)
                        .addComponent(jButtonCleart)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking & Reservation", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jTextField32KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField32KeyReleased
        // TODO add your handling code here:
        jTableDaily.setAutoCreateRowSorter(true);
        try
        {
            String me = jTextField32.getText();
            String sql = "Select * from daily where dId like ? or vId like ? or empID like ? or tripId like ? or dDate like ? ";
            pst = conn.prepareStatement(sql);
            pst.setString(1, me + "%");
            pst.setString(2, me + "%");
            pst.setString(3, me + "%");
            pst.setString(4, me + "%");
            pst.setString(5, me + "%");

            rs = pst.executeQuery();
            jTableDaily.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {

            }
        }
    }//GEN-LAST:event_jTextField32KeyReleased

    private void jTableDailyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDailyMouseClicked
        // TODO add your handling code here:
        int row = jTableDaily.getSelectedRow();
        String tClick = (jTableDaily.getModel().getValueAt(row, 0).toString());
        try
        {
            String sql ="select * from daily where dId="+tClick+" ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next())
            {
                int add1 = rs.getInt("dId");
                jTextFielddaily.setText(String.valueOf(add1));
                int add2 = rs.getInt("vId");
                jComboBoxVid.setSelectedItem(String.valueOf(add2));
                String add3 = rs.getString("dDate");
                ((JTextField)jDateChooserDaily.getDateEditor().getUiComponent()).setText(add3);
                double add4 = rs.getDouble("fuel");
                jTextFieldFuelLitre.setText(String.valueOf(add4));
                double add5 = rs.getDouble("oil");
                jTextFieldOilLitre.setText(String.valueOf(add5));
                String add6 = rs.getString("checkup");
                switch (add6) {
                    case "No":
                    jRadioButtonNo.setSelected(true);
                    break;
                    case "Yes":
                    jRadioButtonYes.setSelected(true);
                    break;
                }
                String add7 = rs.getString("empID");
                jTextFieldDId.setText(add7);
                double add8 = rs.getDouble("cleaning");
                jTextFieldClean.setText(String.valueOf(add8));
                double add9 = rs.getDouble("fuelcost");
                jTextFieldfuelCost.setText(String.valueOf(add9));
                double add10 = rs.getDouble("oilcost");
                jTextFieldOilCost.setText(String.valueOf(add10));
                double add11 = rs.getDouble("driveEarn");
                jTextFielddriveCost.setText(String.valueOf(add11));
                double add12 = rs.getDouble("total");
                jTextFieldtotal.setText(String.valueOf(add12));
                String add13 = rs.getString("tripId");
                jTextFieldTrip.setText(add13);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTableDailyMouseClicked

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete", "Delete",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
            String sql ="delete from daily where dId=?";
            try
            {
                pst = conn.prepareStatement(sql);
                pst.setString(1, jTextFielddaily.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted");
            }
            catch(SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            update_table();
            jTextFielddaily.setText(null);
            jComboBoxVid.setSelectedItem(null);
            ((JTextField)jDateChooserDaily.getDateEditor().getUiComponent()).setText(null);
            jTextFieldFuelLitre.setText(null);
            jTextFieldOilLitre.setText(null);
            buttonGroup1.clearSelection();
            jTextFieldDId.setText(null);
            jTextFieldClean.setText(null);
            jTextFieldfuelCost.setText(null);
            jTextFieldOilCost.setText(null);
            jTextFielddriveCost.setText(null);
            jTextFieldtotal.setText(null);
            jTextFieldTrip.setText(null);
        }
    }//GEN-LAST:event_delActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:

        try
        {
            double clean = Double.parseDouble(jTextFieldClean.getText());
            double fuel = Double.parseDouble(jTextFieldfuelCost.getText());
            double oil = Double.parseDouble(jTextFieldOilCost.getText());
            double drive = Double.parseDouble(jTextFielddriveCost.getText());
            double tot;
            tot = clean + fuel + oil + drive;
            jTextFieldtotal.setText(String.valueOf(tot));

            String sql = "Insert into daily (dId, vId, dDate, fuel, oil, checkup, empID, cleaning, fuelcost, oilcost, driveEarn, total, tripId) "
            + "values (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, jTextFielddaily.getText());
            pst.setString(2, jComboBoxVid.getSelectedItem().toString());
            pst.setString(3, ((JTextField)jDateChooserDaily.getDateEditor().getUiComponent()).getText());
            pst.setDouble(4, Double.parseDouble(jTextFieldFuelLitre.getText()));
            pst.setDouble(5, Double.parseDouble(jTextFieldOilLitre.getText()));
            pst.setString(6, gender);
            pst.setString(7, jTextFieldDId.getText());
            pst.setDouble(8, Double.parseDouble(jTextFieldClean.getText()));
            pst.setDouble(9, Double.parseDouble(jTextFieldfuelCost.getText()));
            pst.setDouble(10, Double.parseDouble(jTextFieldOilCost.getText()));
            pst.setDouble(11, Double.parseDouble(jTextFielddriveCost.getText()));
            pst.setDouble(12, Double.parseDouble(jTextFieldtotal.getText()));
            pst.setString(13, jTextFieldTrip.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null, "Saved");
        }
        catch(SQLException | NumberFormatException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                update_table();
                jTextFielddaily.setText(null);
                jComboBoxVid.setSelectedItem(null);
                ((JTextField)jDateChooserDaily.getDateEditor().getUiComponent()).setText(null);
                jTextFieldFuelLitre.setText(null);
                jTextFieldOilLitre.setText(null);
                buttonGroup1.clearSelection();
                jTextFieldDId.setText(null);
                jTextFieldClean.setText(null);
                jTextFieldfuelCost.setText(null);
                jTextFieldOilCost.setText(null);
                jTextFielddriveCost.setText(null);
                jTextFieldtotal.setText(null);
                jTextFieldTrip.setText(null);
            }
            catch(Exception e)
            {

            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clear_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_txtActionPerformed
        // TODO add your handling code here:
        jTextFielddaily.setText(null);
        jComboBoxVid.setSelectedItem(null);
        ((JTextField)jDateChooserDaily.getDateEditor().getUiComponent()).setText(null);
        jTextFieldFuelLitre.setText(null);
        jTextFieldOilLitre.setText(null);
        buttonGroup1.clearSelection();
        jTextFieldDId.setText(null);
        jTextFieldClean.setText(null);
        jTextFieldfuelCost.setText(null);
        jTextFieldOilCost.setText(null);
        jTextFielddriveCost.setText(null);
        jTextFieldtotal.setText(null);
        jTextFieldTrip.setText(null);
    }//GEN-LAST:event_clear_txtActionPerformed

    private void update_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_txtActionPerformed
        // TODO add your handling code here:
        try
        {

            int vId = Integer.parseInt(jComboBoxVid.getSelectedItem().toString());
            int dId = Integer.parseInt(jTextFielddaily.getText());
            String dDate = ((JTextField)jDateChooserDaily.getDateEditor().getUiComponent()).getText();
            double fLtr = Double.parseDouble(jTextFieldFuelLitre.getText());
            double oLtr = Double.parseDouble(jTextFieldOilLitre.getText());
            String gen = gender;
            String dDrive = jTextFieldDId.getText();
            double clean = Double.parseDouble(jTextFieldClean.getText());
            double fuel = Double.parseDouble(jTextFieldfuelCost.getText());
            double oil = Double.parseDouble(jTextFieldOilCost.getText());
            double drive = Double.parseDouble(jTextFielddriveCost.getText());
            double tot = clean + fuel + oil + drive;
            jTextFieldtotal.setText(String.valueOf(tot));
            double total = Double.parseDouble(jTextFieldtotal.getText());
            String ftrip = jTextFieldTrip.getText();

            String sql = "update daily set dId='"+dId+"' , vId='"+vId+"' , dDate='"+dDate+"' , fuel='"+fLtr+"' , oil='"+oLtr+"' ,"
            + " checkup='"+gen+"' , empID='"+dDrive+"' , cleaning='"+clean+"' , fuelcost='"+fuel+"' , oilcost='"+oil+"', "
            + "driveEarn='"+drive+"' , total='"+total+"' , tripId='"+ftrip+"' where dId='"+dId+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
        }
        catch(NumberFormatException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        update_table();
        jTextFielddaily.setText(null);
        jComboBoxVid.setSelectedItem(null);
        ((JTextField)jDateChooserDaily.getDateEditor().getUiComponent()).setText(null);
        jTextFieldFuelLitre.setText(null);
        jTextFieldOilLitre.setText(null);
        buttonGroup1.clearSelection();
        jTextFieldDId.setText(null);
        jTextFieldClean.setText(null);
        jTextFieldfuelCost.setText(null);
        jTextFieldOilCost.setText(null);
        jTextFielddriveCost.setText(null);
        jTextFieldtotal.setText(null);
        jTextFieldTrip.setText(null);
    }//GEN-LAST:event_update_txtActionPerformed

    private void jTextFieldDIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDIdActionPerformed

    private void jRadioButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoActionPerformed
        // TODO add your handling code here:
        gender = "No";
    }//GEN-LAST:event_jRadioButtonNoActionPerformed

    private void jRadioButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonYesActionPerformed
        // TODO add your handling code here:
        gender = "Yes";
    }//GEN-LAST:event_jRadioButtonYesActionPerformed

    private void jButtonCleartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleartActionPerformed
        // TODO add your handling code here:
        jTextFieldbookRef.setText(null);
        jTextFieldcusName.setText(null);
        jTextFieldpNumber.setText(null);
        jTextFieldkin.setText(null);
        jTextFieldkinPhone.setText(null);
        jComboBoxadult.setSelectedItem(null);
        jComboBoxchild.setSelectedItem(null);
        jComboBoxinfant.setSelectedItem(null);
        ((JTextField)jDateChooserdepartD.getDateEditor().getUiComponent()).setText(null);
        jComboBoxdepartT.setSelectedItem(null);
        jTextFieldDstation.setText(null);
        jTextFieldseatNo.setText(null);
        ((JTextField)jDateChooserreturn.getDateEditor().getUiComponent()).setText(null);
        jTextFieldtripId.setText(null);
        jTextFielddestin.setText(null);
        jComboBoxVID.setSelectedItem(null);
        jTextFieldfareP.setText(null);
    }//GEN-LAST:event_jButtonCleartActionPerformed

    private void jButtondeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete", "Delete",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        String sql ="delete from booking where receiptId=?";
        try
        {
            pst = conn.prepareStatement(sql);
            pst.setString(1, jTextFieldbookRef.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            update_tableBook();
            jTextFieldbookRef.setText(null);
            jTextFieldcusName.setText(null);
            jTextFieldpNumber.setText(null);
            jTextFieldkin.setText(null);
            jTextFieldkinPhone.setText(null);
            jComboBoxadult.setSelectedItem(null);
            jComboBoxchild.setSelectedItem(null);
            jComboBoxinfant.setSelectedItem(null);
            ((JTextField)jDateChooserdepartD.getDateEditor().getUiComponent()).setText(null);
            jComboBoxdepartT.setSelectedItem(null);
            jTextFieldDstation.setText(null);
            jTextFieldseatNo.setText(null);
            ((JTextField)jDateChooserreturn.getDateEditor().getUiComponent()).setText(null);
            jTextFieldtripId.setText(null);
            jTextFielddestin.setText(null);
            jComboBoxVID.setSelectedItem(null);
            jTextFieldfareP.setText(null);
        }
    }//GEN-LAST:event_jButtondeleActionPerformed

    private void jButtonupDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupDActionPerformed
        // TODO add your handling code here:
        try
        {
         
            int rId = Integer.parseInt(jTextFieldbookRef.getText());
            String cusName = jTextFieldcusName.getText();
            int cusFone = Integer.parseInt(jTextFieldpNumber.getText());
            String kin = jTextFieldkin.getText();
            int kinfone = Integer.parseInt(jTextFieldkinPhone.getText());
            int adult = Integer.parseInt(jComboBoxadult.getSelectedItem().toString());
            int child = Integer.parseInt(jComboBoxchild.getSelectedItem().toString());
            int infant = Integer.parseInt(jComboBoxinfant.getSelectedItem().toString());
            String departD = ((JTextField)jDateChooserdepartD.getDateEditor().getUiComponent()).getText();
            String departT = jComboBoxdepartT.getSelectedItem().toString();
            String dStation = jTextFieldDstation.getText();
            String seat = jTextFieldseatNo.getText();
            String returnD = ((JTextField)jDateChooserreturn.getDateEditor().getUiComponent()).getText();
            String tripin = jTextFieldtripId.getText();
            String destin = jTextFielddestin.getText();
            int vid = Integer.parseInt(jComboBoxVID.getSelectedItem().toString());
            double fare = Double.parseDouble(jTextFieldfareP.getText());
        
        String sql = "update booking set receiptId='"+rId+"' , cusName='"+cusName+"' , cusPhone='"+cusFone+"' , kin='"+kin+"' , "
                + "kinPhone='"+kinfone+"' , adult='"+adult+"' , children='"+child+"' , infant='"+infant+"', "
                + "departDate='"+departD+"' , departTime='"+departT+"' , departStation='"+dStation+"' , seatNo='"+seat+"' , "
                + "returnDate='"+returnD+"' , tripId='"+tripin+"' , destination='"+destin+"' , vId='"+vid+"' , "
                + "farePay='"+fare+"' where receiptId='"+rId+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
        }
        catch(NumberFormatException | SQLException | HeadlessException e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
        update_tableBook();
    }//GEN-LAST:event_jButtonupDActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        try
        {
           String sql = "Insert into booking (receiptId, cusName, cusPhone, kin, kinPhone, adult, children, infant, "
                   + "departDate, departTime, departStation, seatNo, returnDate, tripId, destination, vId, farePay ) "
                   + "values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
           pst = conn.prepareStatement(sql);
           pst.setInt(1, Integer.parseInt(jTextFieldbookRef.getText()));
           pst.setString(2, jTextFieldcusName.getText());
           pst.setInt(3, Integer.parseInt(jTextFieldpNumber.getText()));
           pst.setString(4, jTextFieldkin.getText());
           pst.setInt(5, Integer.parseInt(jTextFieldkinPhone.getText()));
           pst.setInt(6, Integer.parseInt(jComboBoxadult.getSelectedItem().toString()));
           pst.setInt(7, Integer.parseInt(jComboBoxchild.getSelectedItem().toString()));
           pst.setInt(8, Integer.parseInt(jComboBoxinfant.getSelectedItem().toString()));
           pst.setString(9, ((JTextField)jDateChooserdepartD.getDateEditor().getUiComponent()).getText());
           pst.setString(10, jComboBoxdepartT.getSelectedItem().toString());
           pst.setString(11, jTextFieldDstation.getText());
           pst.setString(12, jTextFieldseatNo.getText());
           pst.setString(13, ((JTextField)jDateChooserreturn.getDateEditor().getUiComponent()).getText());
           pst.setString(14, jTextFieldtripId.getText());
           pst.setString(15, jTextFielddestin.getText());
           pst.setInt(16, Integer.parseInt(jComboBoxVID.getSelectedItem().toString()));
           pst.setDouble(17, Double.parseDouble(jTextFieldfareP.getText()));
           
           pst.execute();
           
           JOptionPane.showMessageDialog(null, "Saved");
          
        }
        catch(SQLException | NumberFormatException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
       finally
        {
             try
                {
                    update_tableBook();
                    jTextFieldbookRef.setText(null);
                    jTextFieldcusName.setText(null);
                    jTextFieldpNumber.setText(null);
                    jTextFieldkin.setText(null);
                    jTextFieldkinPhone.setText(null);
                    jComboBoxadult.setSelectedItem(null);
                    jComboBoxchild.setSelectedItem(null);
                    jComboBoxinfant.setSelectedItem(null);
                    ((JTextField)jDateChooserdepartD.getDateEditor().getUiComponent()).setText(null);
                    jComboBoxdepartT.setSelectedItem(null);
                    jTextFieldDstation.setText(null);
                    jTextFieldseatNo.setText(null);
                    ((JTextField)jDateChooserreturn.getDateEditor().getUiComponent()).setText(null);
                    jTextFieldtripId.setText(null);
                    jTextFielddestin.setText(null);
                    jComboBoxVID.setSelectedItem(null);
                    jTextFieldfareP.setText(null);
                }
                catch(Exception e)
                {
                
                }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTablebookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablebookingMouseClicked
        // TODO add your handling code here:
        int row = jTablebooking.getSelectedRow();
        String tClick = (jTablebooking.getModel().getValueAt(row, 0).toString());
        try
        {
            String sql ="select * from booking where receiptId="+tClick+" ";
            pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
      
             if(rs.next())
             {
                 int add1 = rs.getInt("receiptId");
                 jTextFieldbookRef.setText(String.valueOf(add1));
                 String add2 = rs.getString("cusName");
                 jTextFieldcusName.setText(add2);
                 int add3 = rs.getInt("cusPhone");
                 jTextFieldpNumber.setText(String.valueOf(add3));
                 String add4 = rs.getString("kin");
                 jTextFieldkin.setText(add4);
                 int add5 = rs.getInt("kinPhone");
                 jTextFieldkinPhone.setText(String.valueOf(add5));
                 int add6 = rs.getInt("adult");
                 jComboBoxadult.setSelectedItem(add6);
                 int add7 = rs.getInt("children");
                 jComboBoxchild.setSelectedItem(add7);
                 int add8 = rs.getInt("infant");
                 jComboBoxinfant.setSelectedItem(add8);
                 String add9 = rs.getString("departDate");
                 ((JTextField)jDateChooserdepartD.getDateEditor().getUiComponent()).setText(add9);
                 String add10 = rs.getString("departTime");
                 jComboBoxdepartT.setSelectedItem(add10);
                 String add11 = rs.getString("departStation");
                 jTextFieldDstation.setText(add11);
                 String add12 = rs.getString("seatNo");
                 jTextFieldseatNo.setText(add12);
                 String add13 = rs.getString("returnDate");
                 ((JTextField)jDateChooserreturn.getDateEditor().getUiComponent()).setText(add13);
                 String add14 = rs.getString("tripId");
                 jTextFieldtripId.setText(add14);
                 String add15 = rs.getString("destination");
                 jTextFielddestin.setText(add15);
                 int add16 = rs.getInt("vId");
                 jComboBoxVID.setSelectedItem(add16);
                 double add17 = rs.getDouble("farePay");                 
                 jTextFieldfareP.setText(String.valueOf(add17));
             }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTablebookingMouseClicked

    private void jComboBoxVidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVidActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBoxVidActionPerformed

    private void jComboBoxVidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxVidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVidKeyPressed

    private void jComboBoxVidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxVidFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVidFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try 
            {
            int id = Integer.parseInt(jComboBoxVid.getSelectedItem().toString());
            String sql = "select * from vehicleDetails where vId= ? ";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            
            while(rs.next())
           {
               String car = rs.getString("make");
               String model = rs.getString("model");
               String color = rs.getString("color");
               String reg = rs.getString("Vreg");
               //jComboBoxVid.setToolTipText(color +" "+ car +" "+ model + " with registration Id: " + reg);
                //jComboBoxVID.setToolTipText(color +" "+ car +" "+ model + " with registration Id: " + reg);
                JOptionPane.showMessageDialog(null, color +" "+ car +" "+ model + " with registration Id: " + reg);
           
           }
            
        } 
        catch (NumberFormatException | SQLException ex) 
        {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
         {
             int id = Integer.parseInt(jTextFieldDId.getText());
             String sql = "select * from employee where empID = '"+id+"'";
             pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
             
             while(rs.next())
             {
                 String fname = rs.getString("fname");
                 String lname = rs.getString("lname");
                 String phone = rs.getString("phone");
                 JOptionPane.showMessageDialog(null, fname +" "+ lname + " with phone number: " + phone);
             }
         }
         catch(NumberFormatException | SQLException | HeadlessException e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try 
            {
            int id = Integer.parseInt(jComboBoxVid.getSelectedItem().toString());
            String sql = "select * from vehicleDetails where vId= ? ";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            
            while(rs.next())
           {
               String car = rs.getString("make");
               String model = rs.getString("model");
               String color = rs.getString("color");
               String reg = rs.getString("Vreg");
               //jComboBoxVid.setToolTipText(color +" "+ car +" "+ model + " with registration Id: " + reg);
                //jComboBoxVID.setToolTipText(color +" "+ car +" "+ model + " with registration Id: " + reg);
                JOptionPane.showMessageDialog(null, color +" "+ car +" "+ model + " with registration Id: " + reg);
           
           }
            
        } 
        catch (NumberFormatException | SQLException ex) 
        {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear_txt;
    private javax.swing.JButton del;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCleart;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtondele;
    private javax.swing.JButton jButtonupD;
    private javax.swing.JComboBox jComboBoxVID;
    private javax.swing.JComboBox jComboBoxVid;
    private javax.swing.JComboBox jComboBoxadult;
    private javax.swing.JComboBox jComboBoxchild;
    private javax.swing.JComboBox jComboBoxdepartT;
    private javax.swing.JComboBox jComboBoxinfant;
    private com.toedter.calendar.JDateChooser jDateChooserDaily;
    private com.toedter.calendar.JDateChooser jDateChooserdepartD;
    private com.toedter.calendar.JDateChooser jDateChooserreturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDaily;
    private javax.swing.JTable jTablebooking;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextFieldClean;
    private javax.swing.JTextField jTextFieldDId;
    private javax.swing.JTextField jTextFieldDstation;
    private javax.swing.JTextField jTextFieldFuelLitre;
    private javax.swing.JTextField jTextFieldOilCost;
    private javax.swing.JTextField jTextFieldOilLitre;
    private javax.swing.JTextField jTextFieldTrip;
    private javax.swing.JTextField jTextFieldbookRef;
    private javax.swing.JTextField jTextFieldcusName;
    private javax.swing.JTextField jTextFielddaily;
    private javax.swing.JTextField jTextFielddestin;
    private javax.swing.JTextField jTextFielddriveCost;
    private javax.swing.JTextField jTextFieldfareP;
    private javax.swing.JTextField jTextFieldfuelCost;
    private javax.swing.JTextField jTextFieldkin;
    private javax.swing.JTextField jTextFieldkinPhone;
    private javax.swing.JTextField jTextFieldpNumber;
    private javax.swing.JTextField jTextFieldseatNo;
    private javax.swing.JTextField jTextFieldtotal;
    private javax.swing.JTextField jTextFieldtripId;
    private javax.swing.JButton save;
    private javax.swing.JButton update_txt;
    // End of variables declaration//GEN-END:variables
}
