/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportmanagement;

import com.sun.glass.events.KeyEvent;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Maxwell
 */
public class Employee extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
     private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;
    private String gender;
    InputStream is = null;
           
    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        conn = dbConnect.cone();
        update_table();
    }

    private void phone(String num)
    {
        Pattern pat = Pattern.compile("\\d(3)\\d(8)");
        Matcher match = pat.matcher(num);
        
        if(!(match.matches()))
        {
            JOptionPane.showMessageDialog(null, "Invalid phone number");
        }
       
    }
    
    private void update_table()
    {
        try{
        String sql = "select * from employee";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jTableEmp.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }
    
    public void ReadImage(String user, JLabel jl){
        try{

            String query = "SELECT pics FROM employee WHERE empID='"+user+"'";
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();

            byte[] imageData = rs.getBytes(1);
            ImageIcon ii = new ImageIcon(imageData);
            Image image = ii.getImage();
            image = image.getScaledInstance(214, 142, Image.SCALE_SMOOTH);
            ii = new ImageIcon(image);
            jl.setIcon(ii);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    public static BufferedImage resize(BufferedImage image, int width, int height) 
    {
    BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
    Graphics2D g2d = (Graphics2D) bi.createGraphics();
    g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
    g2d.drawImage(image, 0, 0, width, height, null);
    g2d.dispose();
    return bi;
    }
    
   /* private void Fillcombo()
    {
        try
        {
           String sql = "select * from employee"; 
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           
           while(rs.next())
           {
               String name = rs.getString("name");
               jComboBox.addItem(name);
           }

        }
        catch(Exception e)
                {
                   JOptionPane.showMessageDialog(null, e); 
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jimage = new javax.swing.JButton();
        jTextImage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextEmpId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFname = new javax.swing.JTextField();
        jTextSurname = new javax.swing.JTextField();
        jTextAddress = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        marital = new javax.swing.JComboBox();
        jDateOB = new com.toedter.calendar.JDateChooser();
        jTextPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextSalary = new javax.swing.JTextField();
        empDate = new com.toedter.calendar.JDateChooser();
        shift = new javax.swing.JComboBox();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jimg = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmp = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldsearch = new javax.swing.JTextField();
        jButtonupdate = new javax.swing.JButton();
        jButtondel = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homeButton.setText("Home Page");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("Employee Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setText("Add New Employee");

        jimage.setText("Attach Image");
        jimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jimage)
                .addGap(18, 18, 18)
                .addComponent(jTextImage, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jimage)
                    .addComponent(jTextImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Employee ID:");

        jLabel4.setText("First Name:");

        jLabel5.setText("Surname:");

        jLabel6.setText("Address:");

        jLabel7.setText("Email:");

        jLabel8.setText("Date Of Birth:");

        jLabel9.setText("Phone Number:");

        jLabel10.setText("Marital status:");

        jLabel11.setText("Employ Date:");

        marital.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married" }));
        marital.setSelectedIndex(-1);

        jTextPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPhoneKeyTyped(evt);
            }
        });

        jLabel12.setText("Salary:");

        jLabel13.setText("Duty Shift:");

        jTextSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSalaryKeyTyped(evt);
            }
        });

        shift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Shift", "Day", "Night" }));
        shift.setSelectedIndex(-1);

        jimg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jimgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(jimg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonAdd.setText("Add Employee");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jTableEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmp);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action Event", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel14.setText("Search:");

        jTextFieldsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldsearchKeyReleased(evt);
            }
        });

        jButtonupdate.setText("Update");
        jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateActionPerformed(evt);
            }
        });

        jButtondel.setText("Delete");
        jButtondel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondelActionPerformed(evt);
            }
        });

        jButtonclear.setText("Clear Fields");
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtondel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonupdate)
                    .addComponent(jButtondel)
                    .addComponent(jButtonclear))
                .addGap(18, 18, 18))
        );

        jLabel15.setText("Gender:");

        buttonGroup_gender.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup_gender.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextEmpId)
                            .addComponent(jTextFname)
                            .addComponent(jTextSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jTextAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jDateOB, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextPhone))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(marital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel12)
                                .addGap(39, 39, 39)
                                .addComponent(jTextSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                                .addComponent(jRadioButton2))
                                            .addComponent(shift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(empDate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 73, Short.MAX_VALUE))
                            .addComponent(jDesktopPane1))
                        .addGap(36, 36, 36))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jTextFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(jDateOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(empDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(shift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(marital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)))
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void jimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        jTextImage.setText(filename);
        
        try
        {
           File image = new File(filename); 
           BufferedImage imagery = ImageIO.read(image);
           BufferedImage resizedImage = resize(imagery,214,142);//resize the image
           FileInputStream fis = new FileInputStream(image);
           ByteArrayOutputStream bos = new ByteArrayOutputStream();
           byte[] buf = new byte[1024];
           for(int readNum; (readNum = fis.read(buf))!= -1;)
           {
               bos.write(buf,0,readNum);
           }
           person_image = bos.toByteArray();
           format = new ImageIcon(resizedImage);
           jimg.setIcon(format);
          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jimageActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String comb = marital.getSelectedItem().toString();
        String shif = shift.getSelectedItem().toString();
        
        Pattern pat = Pattern.compile("\\d{11}");
        Matcher match = pat.matcher(jTextPhone.getText());
        
        if(match.matches())
        {
            try
        {
           String sql = "Insert into employee (empID, fname, lname, address, email, DOB, phone, marital, salary, empDate, shift, pics, gender) "
                   + "values (?,?,?,?,?,?,?,?,?,?,?,?,?)";
           pst = conn.prepareStatement(sql);
           pst.setString(1, jTextEmpId.getText());
           pst.setString(2, jTextFname.getText());
           pst.setString(3, jTextSurname.getText());
           pst.setString(4, jTextAddress.getText());
           pst.setString(5, jTextEmail.getText());
           pst.setString(6, ((JTextField)jDateOB.getDateEditor().getUiComponent()).getText());
           pst.setString(7, jTextPhone.getText());
           pst.setString(8, comb);
           pst.setDouble(9, Double.parseDouble(jTextSalary.getText()));
           pst.setString(10, ((JTextField)empDate.getDateEditor().getUiComponent()).getText());
           pst.setString(11, shif);
           pst.setBytes(12, person_image);
           pst.setString(13, gender);
           
           pst.execute();
           
           JOptionPane.showMessageDialog(null, "Saved");
        }
        catch(SQLException | NumberFormatException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
       finally
        {
             try
                {
                    update_table();
                    jTextEmpId.setText(null);
                    jTextFname.setText(null);
                    jTextSurname.setText(null);
                    jTextAddress.setText(null);
                    jTextEmail.setText(null);
                    ((JTextField)jDateOB.getDateEditor().getUiComponent()).setText(null);
                    jTextPhone.setText(null);
                    marital.setSelectedItem(null);
                    jTextSalary.setText(null);
                    ((JTextField)empDate.getDateEditor().getUiComponent()).setText(null);
                    shift.setSelectedItem(null);
                    jTextImage.setText(null);
                    buttonGroup_gender.clearSelection();
                    jimg.setIcon(null);
                }
                catch(Exception e)
                {
                
                }
        }
            
        }
        
       else
       {
          JOptionPane.showMessageDialog(null, "Invalid phone number");
       }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        // TODO add your handling code here:
        jTextEmpId.setText(null);
        jTextFname.setText(null);
        jTextSurname.setText(null);
        jTextAddress.setText(null);
        jTextEmail.setText(null);
        ((JTextField)jDateOB.getDateEditor().getUiComponent()).setText(null);
        jTextPhone.setText(null);
        marital.setSelectedItem(null);
        jTextSalary.setText(null);
        ((JTextField)empDate.getDateEditor().getUiComponent()).setText(null);
        shift.setSelectedItem(null);
        jTextImage.setText(null);
        buttonGroup_gender.clearSelection();
        jimg.setIcon(null);
    }//GEN-LAST:event_jButtonclearActionPerformed

    private void jButtondelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondelActionPerformed
        // TODO add your handling code here:
         int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete", "Delete",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        String sql ="delete from employee where empID=?";
        try
        {
            pst = conn.prepareStatement(sql);
            pst.setString(1, jTextEmpId.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        update_table();
        jTextEmpId.setText(null);
        jTextFname.setText(null);
        jTextSurname.setText(null);
        jTextAddress.setText(null);
        jTextEmail.setText(null);
        ((JTextField)jDateOB.getDateEditor().getUiComponent()).setText(null);
        jTextPhone.setText(null);
        marital.setSelectedItem(null);
        jTextSalary.setText(null);
        ((JTextField)empDate.getDateEditor().getUiComponent()).setText(null);
        shift.setSelectedItem(null);
        jTextImage.setText(null);
        buttonGroup_gender.clearSelection();
        jimg.setIcon(null);
        }
    }//GEN-LAST:event_jButtondelActionPerformed

    private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateActionPerformed
        // TODO add your handling code here:
        try
        {
            String empid = jTextEmpId.getText();
            String fname = jTextFname.getText();
            String sname = jTextSurname.getText();
            String addr = jTextAddress.getText();
            String email = jTextEmail.getText();
            String date = ((JTextField)jDateOB.getDateEditor().getUiComponent()).getText();
            String phone = jTextPhone.getText();
            String marry = marital.getSelectedItem().toString();
            Double sal = Double.parseDouble(jTextSalary.getText());
            String datee = ((JTextField)empDate.getDateEditor().getUiComponent()).getText();
            String shif = shift.getSelectedItem().toString();
            String gen = gender;
              
            String sql ="update employee set empID='"+empid+"' , fname='"+fname+"' , lname='"+sname+"' , address='"+addr+"' , email='"+email+"', "
                    + "DOB='"+date+"' , phone='"+phone+"' , marital='"+marry+"' , salary='"+sal+"' , empDate='"+datee+"' , shift='"+shif+"' , gender='"+gen+"'   where empId='"+empid+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        update_table();
        jTextEmpId.setText(null);
        jTextFname.setText(null);
        jTextSurname.setText(null);
        jTextAddress.setText(null);
        jTextEmail.setText(null);
        ((JTextField)jDateOB.getDateEditor().getUiComponent()).setText(null);
        jTextPhone.setText(null);
        marital.setSelectedItem(null);
        jTextSalary.setText(null);
        ((JTextField)empDate.getDateEditor().getUiComponent()).setText(null);
        shift.setSelectedItem(null);
        jTextImage.setText(null);
        buttonGroup_gender.clearSelection();
        jimg.setIcon(null);
    }//GEN-LAST:event_jButtonupdateActionPerformed

    private void jTableEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpMouseClicked
        // TODO add your handling code here:
        
         int row = jTableEmp.getSelectedRow();
        String tClick = (jTableEmp.getModel().getValueAt(row, 0).toString());
        try
        {
            String sql ="select * from employee where empId="+tClick+" ";
            pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
       
        jTextImage.setText(null);
        buttonGroup_gender.clearSelection();
             if(rs.next())
             {
                 String add1 = rs.getString("empId");
                 jTextEmpId.setText(add1);
                 String add2 = rs.getString("fname");
                 jTextFname.setText(add2);
                 String add3 = rs.getString("lname");
                 jTextSurname.setText(add3);
                 String add4 = rs.getString("address");
                 jTextAddress.setText(add4);
                 String add5 = rs.getString("email");
                 jTextEmail.setText(add5);
                 String add6 = rs.getString("DOB");
                 ((JTextField)jDateOB.getDateEditor().getUiComponent()).setText(add6);
                 String add7 = rs.getString("phone");
                 jTextPhone.setText(add7);
                 String add8 = rs.getString("marital");
                 marital.setSelectedItem(add8);
                 Double add9 = rs.getDouble("salary");
                 jTextSalary.setText(String.valueOf(add9));
                 String add10 = rs.getString("empDate");
                 ((JTextField)empDate.getDateEditor().getUiComponent()).setText(add10);
                 String add11 = rs.getString("shift");
                 shift.setSelectedItem(add11);
                 String add12 = rs.getString("pics");
                
                
                 String add13 = rs.getString("gender");
                switch (add13) {
                    case "Male":
                        jRadioButton1.setSelected(true);
                        break;
                    case "Female":
                        jRadioButton2.setSelected(true);
                        break;
                }
                 ReadImage(add1,jimg);
             }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTableEmpMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        gender = "Male";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        gender = "Female";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jimgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jimgMouseClicked
        // TODO add your handling code here:
         String id = jTextEmpId.getText();
        String name = jTextFname.getText();
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to change picture", "Update Profile Picture",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            filename = f.getAbsolutePath();
            jTextImage.setText(filename);
            
            try
        {
           File image = new File(filename); 
           BufferedImage imagery = ImageIO.read(image);
           BufferedImage resizedImage = resize(imagery,214,142);//resize the image
           FileInputStream fis = new FileInputStream(image);
           ByteArrayOutputStream bos = new ByteArrayOutputStream();
           byte[] buf = new byte[1024];
           for(int readNum; (readNum = fis.read(buf))!= -1;)
           {
               bos.write(buf,0,readNum);
           }
           person_image = bos.toByteArray();
           format = new ImageIcon(resizedImage);
           jimg.setIcon(format);
          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
        
        String sql ="update employee set image=? where empId='"+id+"'";
        try
        {
            pst = conn.prepareStatement(sql);
            pst.setBytes(1, person_image);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Profile picture of "+name+" has been changed");
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        update_table();
        }
    }//GEN-LAST:event_jimgMouseClicked

    private void jTextFieldsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldsearchKeyReleased
        // TODO add your handling code here:
        jTableEmp.setAutoCreateRowSorter(true);
        try
        {
            String me = jTextFieldsearch.getText();
            String sql = "Select * from employee where fname like ? or empId like ? or lname like ? or phone like ? or gender like ? or salary like ? or DOB like ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, me + "%");
            pst.setString(2, me + "%");
            pst.setString(3, me + "%");
            pst.setString(4, me + "%");
            pst.setString(5, me + "%");
            pst.setString(6, me + "%");
            pst.setString(7, me + "%");
            
            rs = pst.executeQuery();
            jTableEmp.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_jTextFieldsearchKeyReleased

    private void jTextPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPhoneKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))
                && ! (vchar == KeyEvent.VK_ADD)
           )
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextPhoneKeyTyped

    private void jTextSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSalaryKeyTyped
        // TODO add your handling code here:
         char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))
                && ! (vchar == KeyEvent.VK_PERIOD)
                )
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_jTextSalaryKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_gender;
    private com.toedter.calendar.JDateChooser empDate;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtondel;
    private javax.swing.JButton jButtonupdate;
    private com.toedter.calendar.JDateChooser jDateOB;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmp;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEmpId;
    private javax.swing.JTextField jTextFieldsearch;
    private javax.swing.JTextField jTextFname;
    private javax.swing.JTextField jTextImage;
    private javax.swing.JTextField jTextPhone;
    private javax.swing.JTextField jTextSalary;
    private javax.swing.JTextField jTextSurname;
    private javax.swing.JButton jimage;
    private javax.swing.JLabel jimg;
    private javax.swing.JComboBox marital;
    private javax.swing.JComboBox shift;
    // End of variables declaration//GEN-END:variables
}
