/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportmanagement;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Maxwell
 */
public class Maintenance extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault());
    /**
     * Creates new form Maintenance
     */
    public Maintenance() {
        initComponents();
        conn = dbConnect.cone();
        Fillcombo();
        jComboBox2VId.setSelectedItem(null);
        update_table();
    }
    
    private void Fillcombo()
    {
        try
        {
           String sql = "select * from vehicleDetails"; 
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           
           while(rs.next())
           {
               int name = rs.getInt("vId");
               jComboBox2VId.addItem(name);
           }

        }
        catch(Exception e)
                {
                   JOptionPane.showMessageDialog(null, e); 
                }
    }
    
     private void updateCombo()
     {
          Thread comb = new Thread()
                    {
                        public void run()
                        {
                           try
        {
           DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
           String sql = "select * from vehicleDetails"; 
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           
           while(rs.next())
           {
               int name = rs.getInt("vId");
               model.addElement(String.valueOf(name));   
           }
           jComboBox2VId.setModel(model);
             
        }
        catch(Exception e)
                {
                   JOptionPane.showMessageDialog(null, e); 
                } 
                        }
                        
                    };
                    comb.start();
     }
     
     private void update_table()
    {
        try{
        String sql = "select * from main";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable2Main.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }
     

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1MainId = new javax.swing.JTextField();
        jComboBox1Type = new javax.swing.JComboBox();
        jDateChooser1Main = new com.toedter.calendar.JDateChooser();
        jTextFieldCost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Desc = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2Main = new javax.swing.JTable();
        jButton15Save = new javax.swing.JButton();
        jButton16Update = new javax.swing.JButton();
        jButton17Del = new javax.swing.JButton();
        jButton18Clear = new javax.swing.JButton();
        jTextField23Search = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2Replace = new javax.swing.JTextArea();
        jComboBox2VId = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonHome.setText("Home Page");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("Maintenance Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel2.setText("Vehicle  ID:");

        jLabel3.setText("Maintenance Type:");

        jLabel4.setText("Replaced Part:");

        jLabel5.setText("Maintenance Date:");

        jLabel6.setText("Maintenance Cost:");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Maintenance Books");

        jLabel9.setText("Maintenance ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1MainId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField1MainId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jComboBox1Type.setEditable(true);
        jComboBox1Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Battery", "Belts and Hoses", "Brake", "Cooling System", "Filters", "Fluids", "Headlights", "Others", "Suspension", "Tires", "Water", "Wiring", "Windshield & Wipers" }));
        jComboBox1Type.setSelectedIndex(-1);

        jDateChooser1Main.setDateFormatString("yyyy-MMM-dd");

        jLabel8.setText("Description:");

        jTextArea1Desc.setColumns(20);
        jTextArea1Desc.setRows(5);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextArea1Desc, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jTextArea1Desc, org.jdesktop.beansbinding.BeanProperty.create("lineWrap"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(jTextArea1Desc);

        jTable2Main.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2Main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MainMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2Main);

        jButton15Save.setText("Save");
        jButton15Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15SaveActionPerformed(evt);
            }
        });

        jButton16Update.setText("Update");
        jButton16Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16UpdateActionPerformed(evt);
            }
        });

        jButton17Del.setText("Delete");
        jButton17Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17DelActionPerformed(evt);
            }
        });

        jButton18Clear.setText("Clear Fields");
        jButton18Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ClearActionPerformed(evt);
            }
        });

        jTextField23Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField23SearchKeyReleased(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 204));
        jLabel36.setText("Search:");

        jTextArea2Replace.setColumns(20);
        jTextArea2Replace.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextArea2Replace, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jTextArea2Replace, org.jdesktop.beansbinding.BeanProperty.create("lineWrap"));
        bindingGroup.addBinding(binding);

        jScrollPane4.setViewportView(jTextArea2Replace);

        jComboBox2VId.setEditable(true);
        jComboBox2VId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("c");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(jComboBox2VId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1Type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1Main, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCost))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField23Search, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton15Save, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton16Update, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton17Del, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton18Clear)))
                .addContainerGap(258, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(jComboBox2VId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jDateChooser1Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15Save)
                    .addComponent(jButton16Update)
                    .addComponent(jButton17Del)
                    .addComponent(jButton18Clear)
                    .addComponent(jTextField23Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButton17DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17DelActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete", "Delete",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        String sql ="delete from main where mainId=?";
        try
        {
            pst = conn.prepareStatement(sql);
            pst.setString(1, jTextField1MainId.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            update_table();
            jTextField1MainId.setText(null);
            jComboBox2VId.setSelectedItem(null);
            jComboBox1Type.setSelectedItem(null);
            jTextArea2Replace.setText(null);
            ((JTextField)jDateChooser1Main.getDateEditor().getUiComponent()).setText(null);
            jTextFieldCost.setText(null);
            jTextArea1Desc.setText(null);
        }
        
    }//GEN-LAST:event_jButton17DelActionPerformed

    private void jButton15SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15SaveActionPerformed
        // TODO add your handling code here:
        try
        {
           String sql = "Insert into main (mainId, vId, mType, rPart, mDate, mCost, mDesc) "
                   + "values (?,?,?,?,?,?,?)";
           pst = conn.prepareStatement(sql);
           pst.setString(1, jTextField1MainId.getText());
           pst.setString(2, jComboBox2VId.getSelectedItem().toString());
           pst.setString(3, jComboBox1Type.getSelectedItem().toString());
           pst.setString(4, jTextArea2Replace.getText());
           pst.setString(5, ((JTextField)jDateChooser1Main.getDateEditor().getUiComponent()).getText());
           pst.setInt(6, Integer.parseInt(jTextFieldCost.getText()));
           pst.setString(7, jTextArea1Desc.getText());
           
           pst.execute();
           
           JOptionPane.showMessageDialog(null, "Saved");
        }
        catch(SQLException | NumberFormatException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
       finally
        {
             try
                {
                    update_table();
                    jTextField1MainId.setText(null);
                    jComboBox2VId.setSelectedItem(null);
                    jComboBox1Type.setSelectedItem(null);
                    jTextArea2Replace.setText(null);
                    ((JTextField)jDateChooser1Main.getDateEditor().getUiComponent()).setText(null);
                    jTextFieldCost.setText(null);
                    jTextArea1Desc.setText(null);
                }
                catch(Exception e)
                {
                
                }
        }
    
    }//GEN-LAST:event_jButton15SaveActionPerformed

    private void jButton16UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16UpdateActionPerformed
        // TODO add your handling code here:
        try
        {
            
        int vId = Integer.parseInt(jComboBox2VId.getSelectedItem().toString());
        String tId = jComboBox1Type.getSelectedItem().toString();
        int mId = Integer.parseInt(jTextField1MainId.getText());
        String rPart = jTextArea2Replace.getText();
        String mDate = ((JTextField)jDateChooser1Main.getDateEditor().getUiComponent()).getText();
        double cost = Double.parseDouble(jTextFieldCost.getText());
        String mDesc = jTextArea1Desc.getText();
        
        String sql = "update main set mainId='"+mId+"' , vId='"+vId+"' , mType='"+tId+"' , rPart='"+rPart+"' , mDate='"+mDate+"' , mCost='"+cost+"' , mDesc='"+mDesc+"' "
                + "where mainId='"+mId+"'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
        }
        catch(NumberFormatException | SQLException | HeadlessException e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
        update_table();
    }//GEN-LAST:event_jButton16UpdateActionPerformed

    private void jButton18ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ClearActionPerformed
        // TODO add your handling code here:
        jTextField1MainId.setText(null);
        jComboBox2VId.setSelectedItem(null);
        jComboBox1Type.setSelectedItem(null);
        jTextArea2Replace.setText(null);
        ((JTextField)jDateChooser1Main.getDateEditor().getUiComponent()).setText(null);
        jTextFieldCost.setText(null);
        jTextArea1Desc.setText(null);
    }//GEN-LAST:event_jButton18ClearActionPerformed

    private void jTable2MainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MainMouseClicked
        // TODO add your handling code here:
        
        int row = jTable2Main.getSelectedRow();
        String tClick = (jTable2Main.getModel().getValueAt(row, 0).toString());
        try
        {
            String sql ="select * from main where mainId="+tClick+" ";
            pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
      
             if(rs.next())
             {
                 int add1 = rs.getInt("mainId");
                 jTextField1MainId.setText(String.valueOf(add1));
                 int add2 = rs.getInt("vId");
                 jComboBox2VId.setSelectedItem(String.valueOf(add2));
                 String add3 = rs.getString("mType");
                 jComboBox1Type.setSelectedItem(add3);
                 String add4 = rs.getString("rPart");
                 jTextArea2Replace.setText(add4);            
                 Date add5 = rs.getDate("mDate");
                 jDateChooser1Main.setDate(add5);
                 double add6 = rs.getDouble("mCost");
                 jTextFieldCost.setText(String.valueOf(add6));
                 String add7 = rs.getString("mDesc");
                 jTextArea1Desc.setText(add7);
             }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable2MainMouseClicked

    private void jTextField23SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField23SearchKeyReleased
        // TODO add your handling code here:
         jTable2Main.setAutoCreateRowSorter(true);
        try
        {
            String me = jTextField23Search.getText();
            String sql = "Select * from main where mainId like ? or vId like ? or mType like ? or mDate like ? ";
            pst = conn.prepareStatement(sql);
            pst.setString(1, me + "%");
            pst.setString(2, me + "%");
            pst.setString(3, me + "%");
            pst.setString(4, me + "%");
            
            rs = pst.executeQuery();
            jTable2Main.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_jTextField23SearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            int id = Integer.parseInt(jComboBox2VId.getSelectedItem().toString());
            String sql = "select * from vehicleDetails where vId= ? ";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            rs = pst.executeQuery();

            while(rs.next())
            {
                String car = rs.getString("make");
                String model = rs.getString("model");
                String color = rs.getString("color");
                String reg = rs.getString("Vreg");
                //jComboBoxVid.setToolTipText(color +" "+ car +" "+ model + " with registration Id: " + reg);
                //jComboBoxVID.setToolTipText(color +" "+ car +" "+ model + " with registration Id: " + reg);
                JOptionPane.showMessageDialog(null, color +" "+ car +" "+ model + " with registration Id: " + reg);

            }

        }
        catch (NumberFormatException | SQLException ex)
        {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maintenance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15Save;
    private javax.swing.JButton jButton16Update;
    private javax.swing.JButton jButton17Del;
    private javax.swing.JButton jButton18Clear;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JComboBox jComboBox1Type;
    private javax.swing.JComboBox jComboBox2VId;
    private com.toedter.calendar.JDateChooser jDateChooser1Main;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2Main;
    private javax.swing.JTextArea jTextArea1Desc;
    private javax.swing.JTextArea jTextArea2Replace;
    private javax.swing.JTextField jTextField1MainId;
    private javax.swing.JTextField jTextField23Search;
    private javax.swing.JTextField jTextFieldCost;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
