/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportmanagement;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Maxwell
 */
public class Miscellaneous extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Miscellaneous
     */
    public Miscellaneous() {
        initComponents();
        conn = dbConnect.cone();
        update_table();
        Fillcombo();
        jComboBoxVid.setSelectedItem(null);
    }
    
    private void Fillcombo()
    {
        try
        {
           String sql = "select * from vehicleDetails"; 
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           
           while(rs.next())
           {
               String car = rs.getString("make");
               String model = rs.getString("model");
               String color = rs.getString("color");
               String reg = rs.getString("Vreg");
               int name = rs.getInt("vId");
               jComboBoxVid.addItem(name);
               jComboBoxVid.setToolTipText(color +" "+ car +" "+ model + " with registration Id: " + reg);
           }

        }
        catch(Exception e)
                {
                   JOptionPane.showMessageDialog(null, e); 
                }
    }

     private void update_table()
    {
        try{
        String sql = "select * from miscell";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jTableMiscell.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3miscell = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2Pay = new javax.swing.JTextField();
        jComboBox1Tax = new javax.swing.JComboBox();
        jDateChooser1PayDay = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Des = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMiscell = new javax.swing.JTable();
        jButton1Update = new javax.swing.JButton();
        jButton2Save = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jTextField23Search = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jComboBoxVid = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonHome.setText("Home Page");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("Miscellaneous Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 501, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Miscellaneous Books");

        jLabel8.setText("Miscellaneous ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3miscell, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField3miscell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jLabel2.setText("Vehicle ID:");

        jLabel3.setText("Tax type:");

        jLabel4.setText("Paid date:");

        jLabel5.setText("Amount paid:");

        jLabel6.setText("Description/note:");

        jComboBox1Tax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Initial tax", "Quarterly tax", "Half Year tax", "Annual tax", "Lifetime tax" }));
        jComboBox1Tax.setSelectedIndex(-1);

        jTextArea1Des.setColumns(20);
        jTextArea1Des.setRows(5);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextArea1Des, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jTextArea1Des, org.jdesktop.beansbinding.BeanProperty.create("lineWrap"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(jTextArea1Des);

        jTableMiscell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMiscell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMiscellMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableMiscell);

        jButton1Update.setText("Update");
        jButton1Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1UpdateActionPerformed(evt);
            }
        });

        jButton2Save.setText("Save");
        jButton2Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2SaveActionPerformed(evt);
            }
        });

        jButtonDel.setText("Delete");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear fields");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jTextField23Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField23SearchKeyReleased(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 204));
        jLabel36.setText("Search:");

        jComboBoxVid.setEditable(true);

        jButton1.setText("c");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1PayDay, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxVid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jButton2Save, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1Update)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDel)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField23Search, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2Pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxVid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox1Tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooser1PayDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2Save)
                    .addComponent(jButton1Update)
                    .addComponent(jButtonDel)
                    .addComponent(jButtonClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTextField23Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButton1UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1UpdateActionPerformed
        // TODO add your handling code here:
        try
        {    
        int mId = Integer.parseInt(jTextField3miscell.getText());
        int vId = Integer.parseInt(jComboBoxVid.getSelectedItem().toString());
        String tax = jComboBox1Tax.getSelectedItem().toString();
        String pDate = ((JTextField)jDateChooser1PayDay.getDateEditor().getUiComponent()).getText();
        double cost = Double.parseDouble(jTextField2Pay.getText());
        String mDesc = jTextArea1Des.getText();
        
        String sql = "update miscell set miscId='"+mId+"' , vId='"+vId+"' , tax='"+tax+"' , payDate='"+pDate+"' , pay='"+cost+"' , desc='"+mDesc+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
        }
        catch(NumberFormatException | SQLException | HeadlessException e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
        update_table();
    }//GEN-LAST:event_jButton1UpdateActionPerformed

    private void jButton2SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SaveActionPerformed
        // TODO add your handling code here:
        try
        {
           String sql = "Insert into miscell (miscId, vId, tax, payDate, pay, desc) "
                   + "values (?,?,?,?,?,?)";
           pst = conn.prepareStatement(sql);
           pst.setString(1, jTextField3miscell.getText());
           pst.setString(2, jComboBoxVid.getSelectedItem().toString());
           pst.setString(3, jComboBox1Tax.getSelectedItem().toString());
           pst.setString(4, ((JTextField)jDateChooser1PayDay.getDateEditor().getUiComponent()).getText());
           pst.setDouble(5, Double.parseDouble(jTextField2Pay.getText()));
           pst.setString(6, jTextArea1Des.getText());
           
           pst.execute();
           
           JOptionPane.showMessageDialog(null, "Saved");
        }
        catch(SQLException | NumberFormatException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
       finally
        {
             try
                {
                    update_table();
                    jTextField3miscell.setText(null);
                    jComboBoxVid.setSelectedItem(null);
                    jComboBox1Tax.setSelectedItem(null);
                    ((JTextField)jDateChooser1PayDay.getDateEditor().getUiComponent()).setText(null);
                    jTextField2Pay.setText(null);
                    jTextArea1Des.setText(null);
                }
                catch(Exception e)
                {
                
                }
        }
    }//GEN-LAST:event_jButton2SaveActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete", "Delete",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        String sql ="delete from miscell where miscId=?";
        try
        {
            pst = conn.prepareStatement(sql);
            pst.setString(1, jTextField3miscell.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            update_table();
            jTextField3miscell.setText(null);
            jComboBoxVid.setSelectedItem(null);
            jComboBox1Tax.setSelectedItem(null);
            ((JTextField)jDateChooser1PayDay.getDateEditor().getUiComponent()).setText(null);
            jTextField2Pay.setText(null);
            jTextArea1Des.setText(null);
        }
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextField3miscell.setText(null);
        jComboBoxVid.setSelectedItem(null);
        jComboBox1Tax.setSelectedItem(null);
        ((JTextField)jDateChooser1PayDay.getDateEditor().getUiComponent()).setText(null);
        jTextField2Pay.setText(null);
        jTextArea1Des.setText(null);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTableMiscellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMiscellMouseClicked
        // TODO add your handling code here:
        int row = jTableMiscell.getSelectedRow();
        String tClick = (jTableMiscell.getModel().getValueAt(row, 0).toString());
        try
        {
            String sql ="select * from miscell where miscId="+tClick+" ";
            pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
      
             if(rs.next())
             {
                 int add1 = rs.getInt("miscId");
                 jTextField3miscell.setText(String.valueOf(add1));
                 int add2 = rs.getInt("vId");
                 jComboBoxVid.setSelectedItem(String.valueOf(add2));
                 String add3 = rs.getString("tax");
                 jComboBox1Tax.setSelectedItem(add3);
                 String add4 = rs.getString("payDate");
                 ((JTextField)jDateChooser1PayDay.getDateEditor().getUiComponent()).setText(add4);
                 double add6 = rs.getDouble("pay");
                 jTextField2Pay.setText(String.valueOf(add6));
                 String add7 = rs.getString("desc");
                 jTextArea1Des.setText(add7);
             }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTableMiscellMouseClicked

    private void jTextField23SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField23SearchKeyReleased
        // TODO add your handling code here:
         jTableMiscell.setAutoCreateRowSorter(true);
        try
        {
            String me = jTextField23Search.getText();
            String sql = "Select * from miscell where miscId like ? or vId like ? or tax like ? or payDate like ? ";
            pst = conn.prepareStatement(sql);
            pst.setString(1, me + "%");
            pst.setString(2, me + "%");
            pst.setString(3, me + "%");
            pst.setString(4, me + "%");
            
            rs = pst.executeQuery();
            jTableMiscell.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_jTextField23SearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            int id = Integer.parseInt(jComboBoxVid.getSelectedItem().toString());
            String sql = "select * from vehicleDetails where vId= ? ";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            rs = pst.executeQuery();

            while(rs.next())
            {
                String car = rs.getString("make");
                String model = rs.getString("model");
                String color = rs.getString("color");
                String reg = rs.getString("Vreg");
                //jComboBoxVid.setToolTipText(color +" "+ car +" "+ model + " with registration Id: " + reg);
                //jComboBoxVID.setToolTipText(color +" "+ car +" "+ model + " with registration Id: " + reg);
                JOptionPane.showMessageDialog(null, color +" "+ car +" "+ model + " with registration Id: " + reg);

            }

        }
        catch (NumberFormatException | SQLException ex)
        {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Miscellaneous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Miscellaneous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Miscellaneous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Miscellaneous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Miscellaneous().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Update;
    private javax.swing.JButton jButton2Save;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JComboBox jComboBox1Tax;
    private javax.swing.JComboBox jComboBoxVid;
    private com.toedter.calendar.JDateChooser jDateChooser1PayDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMiscell;
    private javax.swing.JTextArea jTextArea1Des;
    private javax.swing.JTextField jTextField23Search;
    private javax.swing.JTextField jTextField2Pay;
    private javax.swing.JTextField jTextField3miscell;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
